Tweaked the usage message and printing functions

diff --git a/shscripts/script-management-package/change-interpreter b/shscripts/script-management-package/change-interpreter
--- a/shscripts/script-management-package/change-interpreter
+++ b/shscripts/script-management-package/change-interpreter
@@ -9,7 +9,12 @@
 # 1.0.1: Option processing introduced.
 #
 ###############################################################
-usage_string="Usage: change-interpreter -f <filename> -i <interpreter>"
+usage_string="
+Usage: change-interpreter -f <filename> -i <interpreter> [-h]
+	-f : Specify target file
+	-i : Specify interpreter
+	-h : Print this message and exit [optional]
+"
 
 # <functions>
 print_usage ( )
@@ -19,7 +24,7 @@ print_usage ( )
 
 print_error_and_die ( )
 {
-	echo "Error: $1" 1>&2
+	echo "Error: $@" 1>&2
 	print_usage
 	exit 1
 }
